name: .NET Core Desktop

on:
  pull_request:
    branches: ["main", "production-*"]

jobs:
  build:
    if: github.head_ref != 'production-web' && github.head_ref != 'production-ims'
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Setting User Secrets
        env:
            CONNECTIONSTRINGS_DEFAULTCONNECTION: ${{ secrets.USERSECRETS_CONNECTIONSTRINGS_DEFAULTCONNECTION }}
            CONNECTIONSTRINGS_STORAGECONNECTION: ${{ secrets.USERSECRETS_CONNECTIONSTRINGS_STORAGECONNECTION }}
            CLIENTID: ${{ secrets.USERSECRETS_CLIENTID }}
            JWT_SIGNINKEY: ${{ secrets.USERSECRETS_JWT_SIGNINKEY }}
        run: |
            dotnet user-secrets set "ConnectionStrings:DefaultConnection" $env:CONNECTIONSTRINGS_DEFAULTCONNECTION --project .\Src\FoodDesire.AppSettings\
            dotnet user-secrets set "ConnectionStrings:StorageConnection" $env:CONNECTIONSTRINGS_STORAGECONNECTION --project .\Src\FoodDesire.AppSettings\
            dotnet user-secrets set "ClientID" $env:CLIENTID --project .\Src\FoodDesire.AppSettings\
            dotnet user-secrets set "Jwt:SignInKey" $env:JWT_SIGNINKEY --project .\Src\FoodDesire.AppSettings\
        shell: pwsh

      - name: Build
        run: dotnet build Src/FoodDesire.sln --configuration ${{ matrix.configuration }}

      - name: Run tests
        run: dotnet test Src/

      - name: Train Recommendation Model
        run: dotnet run --project Src/FoodDesire.ML.Model --configuration ${{ matrix.configuration }}
